### ISSUE TITLE
issue on downloading

### ISSUE THREAD

**Issue by pk97** [jiashaokun/ffmpeg#1]
Following error cam on running the command - `pip install ffmpeg`

`Collecting ffmpeg
  Using cached https://files.pythonhosted.org/packages/34/4a/0dcd8e2b8e8886ebc16355336b8d9d0abed3851dfbc7e9b8400c8ede2017/ffmpeg-1.0.tar.gz
Collecting subprocess (from ffmpeg)
  Could not find a version that satisfies the requirement subprocess (from ffmpeg) (from versions: )
No matching distribution found for subprocess (from ffmpeg)`

edit : I am on unbuntu 18.04LTS

**Comment by heinzchen** [comment]
try this:
pip install ffmpeg-python

**Comment by skeyjia6** [comment]
try again :  pip install ffmpeg   

2018-09-10 repair the bug
