### ISSUE TITLE
安装了ffmpeg为啥还是用不了呢

### ISSUE THREAD

**Issue by AdoShan** [jiashaokun/ffmpeg#5]
安装python然后pip安装的，同方法安装的you-get可以使用。 环境变量加了还是没用。
说不是内部或外部命令也不是可运行的程序或者批处理

**Comment by skeyjia6** [comment]
你本地安装了 ffmpeg 吗？
http://www.ffmpeg.org/download.html
本地要有 ffmpeg 的执行环境变量才行，还有，你可以参考这个项目的语法，这项目老长时间不更新了~~

**Comment by AdoShan** [comment]
> 你本地安装了 ffmpeg 吗？
> http://www.ffmpeg.org/download.html
> 本地要有 ffmpeg 的执行环境变量才行，还有，你可以参考这个项目的语法，这项目老长时间不更新了~~

pip install ffmpeg
安装过了
pip list都有ffmpeg

**Comment by skeyjia6** [comment]
你得先下载 ffmpeg ，pip 安装的只是用于 基于 ffmpeg 使用其命令的一种方式，你可以参考一下 README

**Comment by AdoShan** [comment]
> 你得先下载 ffmpeg ，pip 安装的只是用于 基于 ffmpeg 使用其命令的一种方式，你可以参考一下 README

OK，谢谢大佬
